name: Run Python Script

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 * * * *' # Optional: Run every hour (customize as needed)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Replace with your desired Python version

      # Install dependencies (if required)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Run your Python script
      - name: Run Python Script
        run: |
          python app.py
